#!/bin/sh
# SPDX-License-Identifier: MIT
# lmi-cnss-daemon-wrapper — run the vendor cnss-daemon with the Android
# property shim preloaded (the daemon expects Android property semantics).
export LD_PRELOAD=/usr/lib/lmi/liblmi_android_prop_shim.so
exec /vendor/bin/cnss-daemon
